db.url=jdbc:mysql://localhost:3306/irctc
db.username=root
db.password=tiger
# Email Settings (Example for Gmail using App Password)
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.sender.email=vardhanadhelialternate@gmail.com
mail.sender.password=aagycfbsxtonawik

!aagy cfbs xton awik




!vonqedjwujwjrsgh = app password gmail  


